packages:
  - packages/*
  - apps/*

packageExtensions:
  react-router-devtools:
    dependencies:
      vite-node: ^6.0.0

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract

allowBuilds:
  esbuild: true
  msgpackr-extract: true
